# Generated by Django 4.0.4 on 2022-05-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('is_ut', models.BooleanField(default=False)),
                ('tax', models.PositiveSmallIntegerField(help_text='Tax rate in percentage for state')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Due date')),
                ('paid', models.BooleanField(default=False)),
                ('updated_on', models.DateField(auto_now=True)),
                ('sgst', models.PositiveSmallIntegerField(help_text='Tax rate in percentage for state', verbose_name='State tax')),
                ('cgst', models.PositiveSmallIntegerField(help_text='Tax rate in percentage for CGST', verbose_name='Central tax')),
                ('transaction_type', models.BooleanField(choices=[(True, 'Interstate'), (False, 'Intrastate')], default=False)),
            ],
            options={
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.CreateModel(
            name='TaxDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('issued_on', models.DateField(auto_now_add=True)),
                ('salary_income', models.FloatField(verbose_name='Salary income')),
                ('share_market_income', models.FloatField(verbose_name='Share market income')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tax.tax')),
            ],
        ),
    ]
