# Generated by Django 4.0.4 on 2022-05-17 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
